---
- name: Cambiar contrase単as de usuarios
  hosts: all  # Cambia "tu_host" por el nombre o grupo de hosts en tu inventario de Ansible

  tasks:
    - name: Cambiar contrase単a de usuarios
      become: yes
      vars_files:
        - usuarios.yml
      vars:
        encrypted_password: "{{ item.contrase単a | password_hash('sha512', 65534 | random(0, 65535) ) }}"  # Hash de la contrase単a
      with_items:
        - "{{ usuarios }}"
      user:
        name: "{{ item.nombre_usuario }}"
        password: "{{ encrypted_password }}"
