- name: Combinar archivos JSON en uno solo
  hosts: all
  gather_facts: false

  tasks:
    - name: Leer contenido del primer archivo JSON
      slurp:
        src: "/tmp/remote_service_info_192.168.73.21.json"
      register: file_1_content

    - name: Leer contenido del segundo archivo JSON
      slurp:
        src: "/tmp/remote_service_info_192.168.73.23.json"
      register: file_2_content

    - name: Decodificar contenido del primer archivo JSON
      set_fact:
        json_1: "{{ file_1_content.content | b64decode | from_json }}"

    - name: Decodificar contenido del segundo archivo JSON
      set_fact:
        json_2: "{{ file_2_content.content | b64decode | from_json }}"

    - name: Crear lista con la información de ambos JSON
      set_fact:
        combined_json_list: "{{ [json_1, json_2] }}"

    - name: Crear archivo JSON combinado
      copy:
        content: "{{ combined_json_list | to_json }}"
        dest: "/tmp/combined_json_output.json"
      delegate_to: 192.168.73.21
