# dar_de_alta_usuario.yml
---
- name: Dar de alta a un usuario en hosts
  hosts: all
  
  tasks:
    - name: Verificar si el usuario ya existe
      command: id "{{ nombre_usuario }}"
      register: resultado_comando
      ignore_errors: yes

    - name: Dar de alta al usuario especificado
      become: yes
      user:
        name: "{{ nombre_usuario }}"
        state: present
      when: resultado_comando.rc != 0
