---
- name: Descomprimir archivos ZIP en una carpeta en el servidor remoto
  hosts: all
  become: true
  tasks:
    - name: Listar archivos ZIP en la carpeta
      shell: "ls /rpool/GA14/*.zip"
      register: archivos_zip

    - name: Descomprimir archivos ZIP
      unarchive:
        src: "{{ item }}"
        dest: /rpool/GA14/
      with_items: "{{ archivos_zip.stdout_lines }}"
