---
- name: Eliminar un usuario en Red Hat 8
  hosts: all
  become: yes
  vars:
    usuario_a_eliminar: "nombre_del_usuario"

  tasks:
    - name: Verificar si el usuario existe
      ansible.builtin.getent:
        database: passwd
        key: "{{ usuario_a_eliminar }}"
      register: user_exist

    - name: Eliminar el usuario si existe
      ansible.builtin.user:
        name: "{{ usuario_a_eliminar }}"
        state: absent
        remove: yes
      when: user_exist is not none and user_exist.passwd is defined

    - name: Eliminar el directorio home del usuario si existe
      ansible.builtin.file:
        path: "/home/{{ usuario_a_eliminar }}"
        state: absent
      when: user_exist is not none and user_exist.passwd is defined
