---
- name: eliminar usuario
  hosts: all 
  become: true
  
  tasks:
    - name: Remove the user seleccionado
      ansible.builtin.user:
        name: "{{ nombre_usuario }}"
        state: absent
        remove: yes
