---
- name: eliminar usuario
  hosts: all  # Reemplaza "tu_grupo_de_hosts" por el nombre de tu grupo de hosts definido en el archivo de inventario
  become: true
  
  tasks:
    - name: Remove the user seleccionado
      ansible.builtin.user:
        name: "{{ nombre_usuario }}"
        state: absent
        remove: yes
