---
-  name: user mod passwd
   hosts: all
   become: true

   tasks:
     - name: change passwd
       ansible.builtin.user:
          name: "{{ myuser }}"
          state: present
          password: "{{ '{{ new_password }}' | password_hash('sha512', test_user_salt) }}"
          update_password: 'always'
