---
- hosts: 192.168.73.238

  tasks:
  - name: 'Change user password'
    become: true
    user:
      name: '{{ user_name }}'
      password: '{{ new_password | password_hash('sha512') }}'
      update_password: 'always'
