---
- name: Crear rol y base de datos en PostgreSQL
  hosts: all
  become: yes
  tasks:
    - name: Instalar el m칩dulo psycopg2
      pip:
        name: psycopg2-binary
      become_user: postgres  # Cambia a usuario postgres para instalar el m칩dulo

    - name: Crear un rol en PostgreSQL
      postgresql_user:
        db: pruebas  # Nombre de la base de datos
        name: roberto    # Nombre del rol
        password: 1595  # Contrase침a del rol
        state: present

    - name: Crear una base de datos en PostgreSQL
      postgresql_db:
        name: pruebasdos  # Nombre de la base de datos
        state: present

    - name: Crear un usuario en PostgreSQL y asignarlo al rol
      postgresql_user:
        db: pruebas
        name: roberto    # Nombre de usuario
        password: 1595  # Contrase침a del usuario
        priv: myrole
        state: present
