---
- name: Verificar
  hosts: all
  gather_facts: false

  vars:
    website_url: "{{ pagina }}"
    max_attempts: 10
    delay_seconds: 10
    results: []

  tasks:
    - name: Verificar si la página web está arriba
      uri:
        url: "{{ pagina }}"
        method: GET
        return_content: no
      register: response
      retries: "{{ max_attempts }}"
      delay: "{{ delay_seconds }}"
      failed_when: false
      changed_when: false

    - name: Mostrar si la validación fue exitosa
      debug:
        msg: "El estado es {{ pagina }} : {{ response.status }}"
      when: response.status == 200

    - name: Mostrar mensaje si la validación falla
      debug:
        msg: "La página web no se encuentra {{ pagina }} : {{ response.status }}"
      when: response.status == 503

    - name: Agregar resultados a la variable 'results'
      set_fact:
        results: "{{ results + [{'url': pagina, 'status': response.status}] }}"
        
    - name: Exportar resultados a archivo JSON
      copy:
        content: "{{ results | to_nice_json }}"
        dest: "/var/tmp/resultados.json"
      when: results|length > 0  # Exportar solo si hay resultados en la variable 'results'


