---
- name: Verificar
  hosts: all
  gather_facts: false

  vars:
    website_url: "{{ pagina }}"
    max_attempts: 10
    delay_seconds: 10

  tasks:
    - name: Verificar si la página web está arriba
      uri:
        url: "{{ pagina }}"
        method: GET
        return_content: no
      register: response
      retries: "{{ max_attempts }}"
      delay: "{{ delay_seconds }}"
      failed_when: false
      changed_when: false

    - name: Mostrar si la validación fue exitosa
      debug:
        msg: "El código de estado es {{ response.status }}"
      when: response.status == 200

    - name: Mostrar mensaje si la validación falla
      fail:
        msg: "La página web no está disponible (Código de estado: {{ response.status }})"
      when: response.status != 200


