- name: se levantan servicios
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: servicios a iniciar
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
      loop: "{{ listadoservice }}"
