---
- name: Verificar el estado de un servicio en Linux
  hosts: all
  become: yes
  
  tasks:
    - name: Obtener información sobre los servicios
      shell: "systemctl status {{ item }}"
      loop: "{{ service_names }}"
      register: service_info
      changed_when: false

    - name: Mostrar el estado de los servicios
      debug:
        msg: "{{ item.stdout }}"
      loop: "{{ service_info.results }}"
