---
- name: Verificar el estado de un servicio en Linux
  hosts: all
  become: yes
  
  tasks:
    - name: Obtener información sobre los servicios habilitados
      shell: "systemctl status {{ item }}"
      loop: "{{ service_names }}"
      register: service_info
      changed_when: false
      ignore_errors: true

    - name: Crear archivo JSON con la información
      set_fact:
        json_content: |
          {
            "host": "{{ ansible_host }}",
            "services": [
              {% for item in service_info %}
              {
                "name": "{{ item.item }}",
                "status": "{{ item.stdout }}",
                "rc": "{{ item.rc }}"
              }{% if not loop.last %},{% endif %}
              {% endfor %}
            ]
          }

    - name: Guardar contenido JSON en archivo
      copy:
        content: "{{ json_content }}"
        dest: "/tmp/service_info.json"




