---
- name: Verificar el estado de múltiples servicios en Linux
  hosts: all
  become: true

  tasks:
    - name: Obtener información sobre los servicios habilitados
      shell: systemctl is-active {{ item }}
      loop: "{{ service_names }}"
      register: service_info
      changed_when: false
      ignore_errors: yes  # Ignorar errores en caso de que un servicio no esté activo.

    - name: Crear archivo JSON con la información simplificada
      set_fact:
        json_content: |
          {
            "host": "{{ ansible_host }}",
            "services": [
              {% for item in service_info.results %}
              {
                "name": "{{ item.name }}",
                "status": "{% if item.status == 'active' %}enabled{% else %}disabled{% endif %}"
              }{% if not loop.last %},{% endif %}
              {% endfor %}
            ]
          }

    - name: Mostrar contenido JSON (para verificar)
      debug:
        var: json_content

    # Guardar archivo JSON en el servidor destino
    - name: Guardar archivo JSON en el servidor destino
      lineinfile:
        path: "/tmp/remote_service_info22_{{ ansible_host }}.json"
        line: "{{ json_content }}"
      delegate_to: 192.168.73.21



