---
- name: Verificar el estado de un servicio en Linux
  hosts: all
  become: yes

  tasks:
    - name: Verificar el estado de los servicios
      systemd:
        name: "{{ item }}"
        state: status
      loop: "{{ service_names }}"
      register: service_status

    - name: Mostrar el estado de los servicios
      debug:
        var: service_status.results

