---
- name: Verificar el estado de múltiples servicios en Linux
  hosts: all
  become: true

  tasks:
    - name: Obtener información sobre los servicios habilitados
      shell: systemctl is-active {{ item }}
      loop: "{{ service_names }}"
      register: service_info
      changed_when: false
      ignore_errors: yes  # Ignorar errores en caso de que un servicio no esté activo.

    - name: Crear lista con la información de cada servicio para el host actual
      set_fact:
        services_list: "{{ services_list | default([]) + [{'host': ansible_host, 'name': item.item, 'status': (item.stdout == 'active') | ternary('enabled', 'disabled')}] }}"
      loop: "{{ service_info.results }}"
      delegate_facts: true

    - name: Guardar archivo JSON en el servidor destino
      delegate_to: 192.168.73.21
      copy:
        content: "{{ services_list | to_json }}"
        dest: "/ruta/en/destino/remote_service_info_{{ ansible_host }}.json"





