---
- name: Verificar el estado de un servicio en Linux
  hosts: all
  become: yes

  tasks:
    - name: Verificar el estado del servicio
      service_facts:
        filters:
          name: "{{ item }}"
      loop: "{{ service_name }}"          
      register: service_status

    - name: Mostrar el estado del servicio
      debug:
        var: service_status

