---
- name: Verificar el estado de múltiples servicios en Linux
  hosts: all
  become: true

  tasks:
    - name: Obtener información sobre los servicios habilitados
      command: systemctl is-active {{ item }}
      loop: "{{ service_names }}"
      register: service_info
      changed_when: false
      ignore_errors: true

    - name: Crear lista de servicios con estado simplificado
      set_fact:
        services_list: "{{ services_list | default([]) + [{'host': inventory_hostname, 'name': item.item, 'status': (item.rc == 0) } ] }}"
      loop: "{{ service_info.results }}"

    - name: Mostrar contenido JSON (para verificar)
      debug:
        var: services_list

    - name: Guardar archivo JSON en el servidor destino
      copy:
        content: "{{ services_list | to_nice_json }}"
        dest: "/tmp/remote_service_info_{{ inventory_hostname }}.json"
      delegate_to: 192.168.73.21






