---
- name: Verificar el estado de múltiples servicios en Linux
  hosts: all
  become: true

  tasks:
    - name: Obtener información sobre los servicios habilitados
      systemd:
        name: "{{ item }}"
        state: "query"
      loop: "{{ service_names }}"
      register: service_info
      changed_when: false
      ignore_errors: yes

    - name: Crear lista de servicios con estado simplificado
      set_fact:
        services_list: "{{ services_list | default([]) + [{'host': ansible_host, 'name': item.name, 'status': (item.status == 'active' | ternary('enabled', 'disabled'))}] }}"
      loop: "{{ service_info.results }}"
      when: item.status is defined  # Ignorar los registros sin información del servicio.

    - name: Mostrar contenido JSON (para verificar)
      debug:
        var: services_list

    - name: Guardar archivo JSON en el servidor destino
      copy:
        content: "{{ hostvars | json_query('\"*\".services_list') | flatten | to_nice_json }}"
        dest: "/tmp/remote_service_info_all.json"
      delegate_to: 192.168.73.21






