---
- name: Verificar el estado de múltiples servicios en Linux
  hosts: all
  become: true

  tasks:
    - name: Obtener información sobre los servicios habilitados
      shell: systemctl is-active {{ item }}
      loop: "{{ service_names }}"
      register: service_info
      changed_when: false

    - name: Crear archivo JSON con la información simplificada
      set_fact:
        json_content: |
          {
            "host": "{{ ansible_host }}",
            "services": [
              {% for item in service_info.results %}
              {
                "name": "{{ item.item }}",
                "status": "{% if item.stdout == 'active' %}enabled{% else %}disabled{% endif %}"
              }{% if not loop.last %},{% endif %}
              {% endfor %}
            ]
          }


    - name: Mostrar contenido JSON (para verificar)
      debug:
        var: json_content

    - name: Copiar archivo JSON al host remoto
      copy:
        content: "{{ json_content }}"
        dest: "/tmp/remote_service_info.json"
