# actualizar_sistema.yml
---
- name: Actualizar sistema operativo
  hosts: all  # Cambia "tu_host" por el nombre o grupo de hosts en tu inventario de Ansible
  gather_facts: false
  become: true

  tasks:
    - name: Limitar el archivo de repositorios para Red Hat/CentOS
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
      lineinfile:
        path: /etc/yum.repos.d/CentOS-Base.repo
        regexp: 'baseurl=http://[^/]*/centos/{{ ansible_distribution_major_version }}'
        line: 'baseurl=http://vault.centos.org/centos/{{ ansible_distribution_major_version }}.9/os/x86_64/'
        backup: yes

    - name: Actualizar el sistema para Red Hat/CentOS
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
      yum:
        name: '*'
        state: latest
        exclude: kernel*
      register: actualizacion_redhat
      changed_when: actualizacion_redhat is changed

    - name: Reiniciar si hay actualizaciones
      when: actualizacion_debian.changed or actualizacion_redhat.changed or actualizacion_suse.changed
      reboot:
        msg: "Reiniciando para aplicar las actualizaciones del sistema"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 30
        post_reboot_delay: 30
        test_command: uptime
