---
- name: Actualizar servidores basados en Debian o RedHat y reiniciarlos si es necesario
  become: true
  hosts: all
  tasks:
    - name: Actualizar servidor (vía yum)
      yum:
        update_cache: true
        name: '*'
        state: latest
      when:
        ansible_pkg_mgr == 'yum'
    - name: Actualizar servidor (vía dnf)
      dnf:
        update_cache: true
        name: '*'
        state: latest
      when:
        ansible_pkg_mgr == 'dnf'
    - name: Actualizar servidor (vía apt)
      apt:
        update_cache: true
        name: '*'
        state: latest
      when:
        ansible_pkg_mgr == 'apt'        

