---
- name: Crear sistema de archivos dentro de sistemas de archivos ZFS existentes
  hosts: all
  become: true
  tasks:
    - name: Crear sistema de archivos GA12
      command: zfs create rpool/GA12
