---
- name: Crear sistema de archivos dentro de sistemas de archivos ZFS existentes
  hosts: all
  tasks:
    - name: Create a new file system called myfs in pool rpool with the setuid property turned off
      community.general.zfs:
        name: rpool/myfs
        state: present
        extra_zfs_properties:
          setuid: 'off'
    collections:
      - name: community.general
        version: master
        source: "{{ github_community_general_repo }}"
